### ISSUE TITLE
kiyo

### ISSUE THREAD

**Issue by 43z708** [3box/ceramic-anchor-allowlist#24]
# Team

kiyo

# Discord

kiyo#8414

# Use Case
Offering nodes as a service to other apps

# Overview
3vcpu-3gb-400gb

```
version: "3.7"
services:
    js-ceramic:
        container_name: js-ceramic
        image: ceramicnetwork/js-ceramic:latest
        restart: always
        ports:
            - "7007:7007"
        volumes:
            - ./:/root/.ceramic
            - ./logs:/root/.ceramic/logs
            - ./statestore:/root/.ceramic/statestore
        network_mode: host
        tty: true

    ipfs:
        container_name: ipfs
        image: ceramicnetwork/go-ipfs-daemon:latest
        restart: always
        ports:
            - "5001:5001"
            - "8011:8011"
        volumes:
            - ./data:/data
        network_mode: host
```

## Ceramic State Store persistence
Making periodic volume snapshots

## IPFS Repo persistence:
Making periodic volume snapshots

## Static Egress IP:
http://133.18.228.34

Plz check it out
@v-stickykeys
