### ISSUE TITLE
mattsu2020

### ISSUE THREAD

**Issue by mattsu2020** [3box/ceramic-anchor-allowlist#26]
# Team
mattsu2020

# Discord
mattsu#8949

# Use Case
Offering nodes as a service to other apps

# Overview
4vcpu-8gb-300gb

```
version: "3.7"
services:
      js-ceramic:
          container_name: js-ceramic
          image: ceramicnetwork/js-ceramic:latest
          restart: always
          ports:
              - "7007:7007"
          volumes:
              - ./:/root/.ceramic
              - ./logs:/root/.ceramic/logs
              - ./statestore:/root/.ceramic/statestore
          tty: true

     ipfs:
          container_name: ipfs
          image: ceramicnetwork/go-ipfs-daemon:latest
          restart: always
          ports:
              - "5001:5001"
              - "8011:8011"
          volumes:
              - ./data:/data
          tty: true
```

## Ceramic State Store persistence
Making periodic volume snapshots

## IPFS Repo persistence:
Making periodic volume snapshots

## Static Egress IP:
[100.21.169.124](http://100.21.169.124:7007/api/v0/node/healthcheck)

Please check
@v-stickykeys
