### ISSUE TITLE
Lobster

### ISSUE THREAD

**Issue by vovacodes** [3box/ceramic-anchor-allowlist#7]
# Team

Lobster

# Discord
vova#4412

# Use Case
Publishing platform on Solana (and Ceramic).

# Overview
Running the following `docker-compose.yml` on a `s-4vcpu-8gb` DigitalOcean droplet with a mounted `100GB` volume

```yml
version: "3.9"

services:
  ipfs:
    image: ceramicnetwork/go-ipfs-daemon:latest
    container_name: ipfs
    ports:
      - "127.0.0.1:5001:5001" # API (Local)
      - "8011:8011" # Healthcheck (Public)
      - "4012:4012" # Swarm WS over SSL (Public)
    volumes:
      - /mnt/lobster_ceramic_data/ipfs:/data/ipfs

  ceramic:
    image: ceramicnetwork/js-ceramic:latest
    container_name: js-ceramic
    ports:
      - "7007:7007" # HTTP (Public)
    volumes:
      - /opt/lobster/ceramic/daemon.config.json:/root/.ceramic/daemon.config.json # Path to daemon config file
      - /opt/lobster/ceramic/logs:/root/.ceramic/logs # Path to daemon logs
      - /mnt/lobster_ceramic_data/ceramic/statestore:/root/.ceramic/statestore # Path to daemon state store
```

## Ceramic State Store persistence
Making periodic volume snapshots

## IPFS Repo persistence:
Making periodic volume snapshots

## Static Egress IP:
143.198.249.20
